sudo: false
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
  - "3.6"
before_install:
  # http://conda.pydata.org/docs/travis.html
  #- sudo apt-get update  # drop sudo to get a faster booting container environment
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
install:
  # Useful for debugging any issues with conda
  - conda info -a
  # Create test environment and install deps
  - conda env create -q -n test-environment python=$TRAVIS_PYTHON_VERSION -f environment.yml
  - source activate test-environment
  # Install
  - python setup.py install build_ext --inplace
script:
  - pytest
